### ISSUE TITLE
Feature Request: Display TX hash on the trace page

### ISSUE THREAD

**Issue by salparadi** [openchainxyz/openchain-monorepo#4]
It would be nice to have the transaction hash displayed at the top of the page with all the other details. Yes I can copy it out of the URL, but it doesn't display anywhere on the page with a handy copy icon. Probably right above "Status" and just say "Hash: 0xXXXX" Thanks, love the site!

**Comment by samczsun** [comment]
Done!

**Comment by salparadi** [comment]
Awesome, TY!
